PhysicianSearch/Models/Search.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhysicianSearch.Models
{
    public class Search
    {
        public Search()
        {
            Physicians = new List<Physician>();
            currentFacets = new CurrentFacets();
            returnedFacets = new ReturnedFacets();
        }

        public List<Physician> Physicians { get; set; }

        public CurrentFacets currentFacets { get; set; }

        public ReturnedFacets returnedFacets { get; set; }

        public int TotalDocs { get; set; }

        public int Start { get; set; }

        public int Rows { get; set; }

    }
}

PhysicianSearch/Controllers/SearchController.cs
using PhysicianSearch.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhysicianSearch.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult getViews()
        {
            // get params
            string q = Request.Params.Get("query");
            string specialties = Request.Params.Get("specialty");
            string genders = Request.Params.Get("gender");

            // build query
            Respository.ExecuteSearch searchLibrary = new Respository.ExecuteSearch();
            PhysicianQuery query = new PhysicianQuery();
            query.Query = q;

            // add filters
            if (specialties != null && specialties != "")
            {
                List<string> s = specialties.Split(',').ToList();
                foreach (string item in s)
                {
                    query.SpecialtyFilter.Add(item);
                }
            }

            if (genders != null && genders != "")
            {
                List<string> g = genders.Split(',').ToList();
                foreach (string item in g)
                {
                    query.GenderFilter.Add(item);
                }
            }

            // query solr
            QueryResponse response = searchLibrary.DoSearch(query);

            // load model
            Search model = new Search();
            model.Physicians = response.Results;
            model.currentFacets.SpecialtyFacet = specialties.Split(',').ToList();
            model.currentFacets.GenderFacet = genders.Split(',').ToList();
            model.returnedFacets.SpecialtyFacet = response.SpecialtyFacet;
            model.returnedFacets.GenderFacet = response.GenderFacet;
            model.Start = query.Start;
            model.Rows = query.Rows;
            model.TotalDocs = response.TotalHits;

            // return partials as json
            var searchResultsView = Helper.RenderViewToString.RenderView(this.ControllerContext, "_SearchResults", model);
            var specialtiesFacetsView = Helper.RenderViewToString.RenderView(this.ControllerContext, "_SpecialtiesFacets", model);
            var genderFacetsView = Helper.RenderViewToString.RenderView(this.ControllerContext, "_GenderFacets", model);
            var paginationView = Helper.RenderViewToString.RenderView(this.ControllerContext, "_Pagination", model);
            var json = Json(new { searchResultsView, specialtiesFacetsView, genderFacetsView, paginationView });
            return json;
        }

        [HttpPost]
        public JsonResult getTypeahead()
        {
            // get params
            string q = Request.Params.Get("query");

            // build query
            Respository.ExecuteSearch searchLibrary = new Respository.ExecuteSearch();
            PhysicianQuery query = new PhysicianQuery();
            query.Query = q;

            // query solr
            QueryResponse response = searchLibrary.DoTypeahead(query);

            // load model
            Search model = new Search();
            model.Physicians = response.Results;

            List<Typeahead> ta = new List<Typeahead>();
            foreach (var item in model.Physicians) {
                Typeahead test = new Typeahead();
                test.label = item.FirstName + " " + item.LastName + " " + item.Degree;
                test.value = item.FirstName + " " + item.LastName;
                test.link = item.FullPath;
                test.type = "physician";
                ta.Add(test);
            }

            return Json(ta);
        }

        [HttpPost]
        public JsonResult getFacets()
        {

            // build query
            Respository.ExecuteSearch searchLibrary = new Respository.ExecuteSearch();
            PhysicianQuery query = new PhysicianQuery();
            query.Query = "*:*";

            // query solr
            QueryResponse response = searchLibrary.DoSearch(query);

            // load model
            //Search model = new Search();
            //model.returnedFacets.SpecialtyFacet = response.SpecialtyFacet;
            //model.returnedFacets.GenderFacet = response.GenderFacet;

            List<KeyValuePair<string, List<Typeahead>>> facets = new List<KeyValuePair<string, List<Typeahead>>>();

            List<Typeahead> specialty = new List<Typeahead>();
            foreach (var item in response.SpecialtyFacet)
            {
                Typeahead ta = new Typeahead();
                ta.label = item.Key;
                ta.value = item.Key;
                ta.link = "";
                ta.type = "specialty";
                specialty.Add(ta);
            }
            facets.Add(new KeyValuePair<string, List<Typeahead>>("Specialty", specialty));

            return Json(facets);
        }
    }
}

PhysicianSearch/Views/Search/Index.cshtml
@model PhysicianSearch.Models.Search

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<div class="row">
    <div class="col-md-3">

        <form action='@Url.Action("Query", "Search")' method="post">
            <input id="query" type="text" name="query" />
            <input type="submit" value="Submit" />
            <hr />
        </form>

        <div class="facets">
            <div class="specialties">

            </div>

            <div class="genders">

            </div>
        </div>

    </div>

    <div class="col-md-9">
        <div class="results">

        </div>

        <div class="pagination">

        </div>
    </div>
</div>
<script>
    var initSpecialties;

    $(document).ready(function () {
        getFacets();

        $('form').on('submit', function (e) {
            e.preventDefault();
            querySolr();
        });

        $('#query').autocomplete({
            source: function (request, response) {
                var specialties = $.ui.autocomplete.filter(initSpecialties, request.term);

                $.ajax({
                    type: "POST",
                    url: "/Search/getTypeahead",
                    data: "query=" + request.term,
                    dataType: "json",
                    success: function (data) {
                        response(data.concat(specialties));
                    }
                })
            },
            minLength: 3
        })
    });

    function querySolr() {
        query = $('#query').val();
        specialties = '&specialty=' + $('input[name="specialty"]:checkbox:checked').map(function () {
            return this.value;
        }).get().join(',');
        genders = '&gender=' + $('input[name="gender"]:checkbox:checked').map(function () {
            return this.value;
        }).get().join(',');

        $.ajax({
            type: "POST",
            url: "/Search/GetViews",
            data: "query=" + query + specialties + genders,
            success: function (response) {
                if (response != null) {
                    $('.results').html(response.searchResultsView);
                    $('.specialties').html(response.specialtiesFacetsView);
                    $('.genders').html(response.genderFacetsView);
                    $('.pagination').html(response.paginationView);
                }
            },
            error: function (response) {
                console.log(response);
            }
        })
    }

    function getFacets() {
        $.ajax({
            type: "POST",
            url: "/Search/GetFacets",
            success: function (response) {
                if (response != null) {
                    initSpecialties = response[0].Value;
                }
            },
            error: function (response) {
                console.log(response);
            }
        })
    }
</script>

PhysicianSearch/Views/Search/_GenderFacets.cshtml
@model PhysicianSearch.Models.Search

<strong>Gender</strong><br />
@if (Model != null)
{
    foreach (KeyValuePair<string, int> gender in Model.returnedFacets.GenderFacet)
    {
        var exists = (Model.currentFacets.GenderFacet.Contains(@gender.Key)) ? "checked=\"checked\"" : "";
        <input type="checkbox" name="gender" value="@gender.Key" onchange="querySolr()" @exists /> @gender.Key <span>-</span> @gender.Value<br />
    }
}
<hr />

PhysicianSearch/Views/Search/_SearchResults.cshtml
@model PhysicianSearch.Models.Search

@if (Model != null)
{
    <span>Number Found: </span> @Model.TotalDocs
    foreach (var item in Model.Physicians)
    {
        <hr />
        <div>
            @item.FirstName @item.LastName @item.Degree <br />
            @item.Specialty
        </div>
    }
}

PhysicianSearch/Views/Search/_SpecialtiesFacets.cshtml
@model PhysicianSearch.Models.Search

<strong>Specialties</strong><br />
@if (Model != null)
{
    foreach (KeyValuePair<string, int> specialty in Model.returnedFacets.SpecialtyFacet)
    {
        var exists = (Model.currentFacets.SpecialtyFacet.Contains(@specialty.Key)) ? "checked=\"checked\"" : "";
        <input type="checkbox" name="specialty" value="@specialty.Key" onchange="querySolr()" @exists /> @specialty.Key <span>-</span> @specialty.Value<br />
    }
}
<hr />

PhysicianSearch/Views/Search/_pagination.cshtml
@model PhysicianSearch.Models.Search

@if (Model != null)
{
    var start = Model.Start;
    var rows = Model.Rows;
    var total = Model.TotalDocs;

    for (int i = 0; i < (total + rows - 1)/rows; i++)
    {
        <a onclick="test(@(i + 1))">@(i + 1)</a>
    }

    <script>
        function test(e) {
            alert(e);
        }
    </script>
}